### ISSUE TITLE
Refactoring of DB

### ISSUE THREAD

**Issue by EnoRage** [button-tech/utils-node-tool#3]
https://github.com/button-tech/utils-node-tool/blob/master/shared/db/db.go#L72

No need for bool return,
Also Add method is not adding anything to DB. We need to rename to Update**

**Comment by prazd** [comment]
Fixed bool return

In AddToStoppedList function we append node address to list:
stoppedList := append(entry.Stopped, address), and then we update entry(list with stopped nodes) in DB
When we use this func, we can only ADD value to the stopped list

So, I think it's not a bad naming.
